name: Test on push

on:
  push:
    branches: [ master ]

jobs:
  test-mac:
    needs: permission
    runs-on: macos-latest
    env:
      DBGSYNCLOG: trace
      DBGSYNCON: true
    steps:
    - name: Set up Go ^1.13
      uses: actions/setup-go@v3
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Test without coverage
      run: make test

  test-windows:
    needs: permission
    runs-on: windows-latest
    env:
      DBGSYNCLOG: trace
      DBGSYNCON: true
    steps:
    - name: Set up Go ^1.13
      uses: actions/setup-go@v3
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Test without coverage
      run: make test

  test-ubuntu:
    needs: permission
    runs-on: ubuntu-latest
    env:
      DBGSYNCLOG: trace
      DBGSYNCON: true
    steps:
    - name: Set up Go ^1.13
      uses: actions/setup-go@v3
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Test with coverage
      run: make coverage

    - name: SonarCloud scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=dedis
          -Dsonar.projectKey=dedis_kyber
          -Dsonar.go.tests.reportPaths=report.json
          -Dsonar.go.coverage.reportPaths=profile.cov
          -Dsonar.pullrequest.key=${{ github.event.number }}
          -Dsonar.pullrequest.branch=${{ github.head_ref }}
          -Dsonar.pullrequest.base=${{ github.event.pull_request.base }}
          -Dsonar.c.file.suffixes=-
          -Dsonar.cpp.file.suffixes=-
          -Dsonar.objc.file.suffixes=-

    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov

  test-ubuntu-x86:
    needs: permission
    runs-on: ubuntu-latest
    env:
      DBGSYNCLOG: trace
      DBGSYNCON: true
    steps:
    - name: Setup Alpine Linux
      uses: jirutka/setup-alpine@v1
      with:
        arch: x86
        packages: >
          go 
          make 
          git 
          gcc 
          musl-dev

    - name: Set up Go ^1.13 for x86
      uses: actions/setup-go@v3
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory for x86
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Test without coverage for x86
      run: make test