name: CI Workflow for tests

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [ master ]

jobs:
  permission:
    if: ${{ github.event_name == 'pull_request_target' }}
    strategy:
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Add comment if PR permission failed
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'safe PR') }}
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🔒 Could not start CI tests due to missing *safe PR* label. Please contact a DEDIS maintainer.'
          })
    - name: Check permission
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'safe PR') }}
      run: |
        echo "::error:: Could not start CI tests due to missing *safe PR* label."
        exit 1

  test:
    needs: [permission]
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        size: ['64b', '32b']
        golang: ['1.21.10', '1.22.3']
        exclude:
          - os: windows-latest
            size: '32b'
          - os: macos-latest
            size: '32b'

    runs-on: ${{ matrix.os }}
    env:
      DBGSYNCLOG: trace
      DBGSYNCON: true

    steps:
    - name: Set up Go ${{ matrix.golang }}
      uses: actions/setup-go@v5
      if: ${{ matrix.size == '64b' }}
      with:
        go-version: ${{ matrix.golang }}
        check-latest: false

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Setup Alpine Linux
      uses: jirutka/setup-alpine@v1
      if: ${{ matrix.size == '32b' }}
      with:
        arch: x86
        packages: >
          make 
          git 
          gcc 
          musl-dev

    - name: Test without coverage (Windows, MacOS)
      if: ${{ matrix.os == 'macos-latest' || matrix.os == 'windows-latest' }}
      run: make test

    - name: Test without coverage (Ubuntu x86)
      if: ${{ matrix.size == '32b' }}
      run: |
        cd ..
        wget -O go.tgz -nv https://go.dev/dl/go${{matrix.golang}}.linux-386.tar.gz
        tar -xzf go.tgz
        export PATH=$PATH:$(pwd)/go/bin
        cd kyber
        make test
      shell: alpine.sh {0}

    - name: Test with coverage
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.size == '64b' }}
      run: make coverage

    - name: SonarCloud scan
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.size == '64b' }}
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=dedis
          -Dsonar.projectKey=dedis_kyber
          -Dsonar.go.tests.reportPaths=report.json
          -Dsonar.go.coverage.reportPaths=profile.cov
          -Dsonar.pullrequest.key=${{ github.event.number }}
          -Dsonar.pullrequest.branch=${{ github.head_ref }}
          -Dsonar.pullrequest.base=${{ github.event.pull_request.base }}
          -Dsonar.c.file.suffixes=-
          -Dsonar.cpp.file.suffixes=-
          -Dsonar.objc.file.suffixes=-

    - name: Send coverage
      if: ${{ github.event_name == 'push' && matrix.os == 'ubuntu-latest' && matrix.size == '64b' }}
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
